---
- name: 'Chocolatey Package Management Demo'
  hosts: 'role_webserver'
  gather_facts: false
  become: true
  become_method: runas
  become_user: SYSTEM
  
  vars:
    nexus_base: 'https://chocolatey.allwayshype.com/nexus/repository'
    nexus_url: '{{ nexus_base }}/ChocolateyInternal/index.json'
    choco_install_script: '{{ nexus_base }}/choco-install/ChocolateyInstall.ps1'
    nexus_password: "{{ lookup('ansible.builtin.env', 'NEXUS_PASSWORD') }}"
    c4b_cert: "{{ lookup('ansible.builtin.env', 'C4B_CERT') }}"

  pre_tasks:
    - name: Set up Arc SSH proxy
      azure.azcollection.azure_rm_arcssh:
        auth_source: cli
        inventory_hostname: "{{ item }}"
        ansible_host: "{{ hostvars[item].ansible_host }}"
        local_user: "{{ hostvars[item].ansible_user }}"
        resource_group: "{{ hostvars[item].resource_group }}"
        resource_type: "{{ hostvars[item].resource_type }}"
        ssh_config_file: "/tmp/{{ hostvars[item].resource_group }}-{{ item }}/ssh_config"
        ssh_relay_file: "/tmp/{{ hostvars[item].resource_group }}-{{ item }}/relay_info"
        ssh_proxy_folder: "~/.clientsshproxy"
      loop: "{{ groups['arc_servers'] | default([]) }}"
      delegate_to: localhost
      run_once: true

    - name: Gather facts
      ansible.builtin.setup:
  
  tasks:
    - name: 'Ensure "git" package is installed'
      chocolatey.chocolatey.win_chocolatey:
        name: 'git'
        state: 'present'

    - name: 'Ensure latest version of "7zip" package is installed'
      chocolatey.chocolatey.win_chocolatey:
        name: '7zip'
        state: 'latest'

    - name: 'Ensure specific version of "nodejs" package is installed... and pinned'
      chocolatey.chocolatey.win_chocolatey:
        name: 'nodejs'
        version: '18.16.0'
        state: 'downgrade'
        pinned: yes

    - name: 'Ensure "notepadplusplus" package is installed, with installer argument'
      chocolatey.chocolatey.win_chocolatey:
        name: 'notepadplusplus'
        state: 'present'
        install_args: '/D=C:\Apps\notepad++'

    - name: 'Ensure "vscode" package is installed, with package parameters'
      chocolatey.chocolatey.win_chocolatey:
        name: 'vscode'
        state: 'present'
        package_params: '/NoDesktopIcon /NoContextMenuFiles /NoContextMenuFolders'
...