# Import variables shared by all deployments
- name: Import Variables
  ansible.builtin.include_vars:
    file: apps.yml

# Set Datadog Agent Update Variable
- name: Set an environment variable for all users
  ansible.windows.win_environment:
    state: present
    name: DD_REMOTE_UPDATES
    value: true
    level: machine

# Install Datadog
- name: Install and Configure Datadog
  ansible.builtin.import_role:
    name: datadog.dd.agent

- name: Reboot
  ansible.windows.win_reboot:
