- name: VM Build
  hosts: all
  connection: winrm
  gather_facts: true

  tasks:
    - name: Gather Custom Windows Facts 
      block:
        - name: Create Windows DIR
          ansible.windows.win_file:
            path: C:\Temp\facts
            state: directory

        - name: Copy pwsh script to windows servers 
          ansible.windows.win_copy:
            src: scripts/get_facts.ps1
            dest: "C:\\Temp\\facts\\"

        - name: Add facts to variable
          ansible.builtin.setup:
            fact_path: C:\TEMP\facts
          register: win_fact

    - name: Rename server to match inventory hostname
      ansible.windows.win_hostname:
        name: "{{ inventory_hostname }}"
      register: rename_result
      
    - name: Chocolatey Install 
      ansible.builtin.include_tasks: chocolatey.yml
    
    - name: Reboot to apply pending changes
      ansible.windows.win_reboot:
      when: rename_result.reboot_required

- import_playbook: playbooks/onboarding_arc.yml
