---
- name: Terraform operations
  hosts: localhost
  gather_facts: false
  become: false
  environment:
    ARM_TENANT_ID: "{{ lookup('ansible.builtin.env', 'ARM_TENANT_ID') }}"
    ARM_SUBSCRIPTION_ID: "{{ lookup('ansible.builtin.env', 'ARM_SUBSCRIPTION_ID') }}"
    ARM_CLIENT_ID: "{{ lookup('ansible.builtin.env', 'ARM_CLIENT_ID') }}"

  vars:
    tf_project_dir: "01-terraform/03-windows-vm"
    tf_project_key: "mgr-of-configs/03-windows-vm.tfstate"
    backend_conf: "{{ lookup('ansible.builtin.env', 'TF_BACKEND_CONFIG_FILE') }}"

  tasks:
    - name: Terraform apply | provision Windows VM
      cloud.terraform.terraform:
        project_path: "{{ tf_project_dir }}"
        state: present
        force_init: true
        backend_config:
          key: "{{ tf_project_key }}"
          resource_group_name: "{{ lookup('ansible.builtin.env', 'ARM_RG_NAME') }}"
          storage_account_name: "{{ lookup('ansible.builtin.env', 'ARM_STG_NAME') }}"
          container_name: "{{ lookup('ansible.builtin.env', 'ARM_CONTAINER_NAME') }}"
          use_azuread_auth: true

    - name: Terraform destroy | provision Windows VM
      tags: [never, remove]
      cloud.terraform.terraform:
        project_path: "{{ tf_project_dir }}"
        state: absent
        force_init: true
        backend_config:
          key: "{{ tf_project_key }}"
          resource_group_name: "{{ lookup('ansible.builtin.env', 'ARM_RG_NAME') }}"
          storage_account_name: "{{ lookup('ansible.builtin.env', 'ARM_STG_NAME') }}"
          container_name: "{{ lookup('ansible.builtin.env', 'ARM_CONTAINER_NAME') }}"
          use_azuread_auth: true