---
# Dynamic inventory from Azure.
# Prerequisites:
#   pip3 install ansible ansible-lint pywinrm
#   ansible-galaxy collection install azure.azcollection
#   az login

plugin: azure.azcollection.azure_rm
auth_source: cli

include_vm_resource_groups:
  - "*"

include_arc_resource_groups:
  - mgr-of-configs

plain_host_names: true

keyed_groups:
  - key: tags.role
    prefix: role
    separator: '_'
  - key: tags.environment
    prefix: env
    separator: '_'

conditional_groups:
  ansible_managed: "'ansible' in (tags.managed_by | default(''))"

exclude_host_filters:
  - tags.managed_by | default('') != 'ansible'

compose:
  ansible_host: "public_ipv4_address | first if resource_type == 'Microsoft.Compute/virtualMachines' else name"
  ansible_user: "'vm_admin' if resource_type == 'Microsoft.Compute/virtualMachines' else lookup('env', 'SRV_ADMIN_USER')"
  ansible_password: "lookup('env', 'ANSIBLE_WINDOWS_PASSWORD') if resource_type == 'Microsoft.Compute/virtualMachines' else lookup('env', 'SRV_ADMIN_PASSWORD')"
  ansible_connection: "'winrm' if resource_type == 'Microsoft.Compute/virtualMachines' else 'ssh'"
  ansible_winrm_transport: "'ntlm'"
  ansible_winrm_server_cert_validation: "'ignore'"
  ansible_winrm_port: "5986"
  ansible_winrm_scheme: "'https'"
  ansible_shell_type: "'powershell'"
  ansible_ssh_common_args: "'-F /tmp/' + resource_group + '-' + name + '/ssh_config' if resource_type == 'Microsoft.HybridCompute/machines' else ''"
...