---
- name: Remove Azure Arc Agent from Windows Servers
  hosts: all
  gather_facts: true
  vars_files:
    - ../demo/vars/secrets.yml
    - ../vars/azure.yml

  tasks:
    - name: Disconnect from Azure Arc
      win_shell: '& "$env:ProgramFiles\AzureConnectedMachineAgent\azcmagent.exe" disconnect --service-principal-id "{{ azure.service_principal_id }}" --service-principal-secret "{{ azure.service_principal_secret }}"'
      ignore_errors: true

    - name: Uninstall Azure Connected Machine Agent
      win_package:
        path: C:\AzureConnectedMachineAgent.msi
        state: absent
      ignore_errors: true

    - name: Remove installer MSI
      ansible.windows.win_file:
        path: C:\AzureConnectedMachineAgent.msi
        state: absent
      ignore_errors: true

    - name: Remove agent data directory
      ansible.windows.win_file:
        path: C:\ProgramData\AzureConnectedMachineAgent
        state: absent
      ignore_errors: true