- name: Test Connection with ping
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
    ansible_winrm_scheme: https
  tasks:
    - name: Ansible Playbook example
      win_ping: