---
- name: Demo Ansible vault
  hosts: localhost
  gather_facts: false
  become: false

  vars_files:
    - vars/secrets.yml

  tasks:
    - name: Lookup credentials from Ansible variables
      ansible.builtin.debug:
        msg: > 
          ansible vars:
          {{ vault_demo_user | default('undefined') }} (user) /
          {{ vault_demo_password | default('undefined') }} (password) /
          {{ vault_sp_id | default('undefined') }} (sp_id) /
          {{ vault_sp_secret | default('undefinded') }} (sp_secret)