name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.repository }}-lint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  statuses: write

jobs:
  superlinter:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      # see: https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      # see: https://github.com/actions/cache/releases/tag/v5.0.4
      - name: Cache Super-Linter image
        id: cache
        uses: actions/cache@v5.0.4
        with:
          path: /tmp/super-linter-slim-v8.5.0.tar
          key: super-linter-slim-v8.5.0

      - name: Load cached image
        if: steps.cache.outputs.cache-hit == 'true'
        run: docker load < /tmp/super-linter-slim-v8.5.0.tar

      - name: Pull and save image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker pull ghcr.io/super-linter/super-linter:slim-v8.5.0
          docker save ghcr.io/super-linter/super-linter:slim-v8.5.0 > /tmp/super-linter-slim-v8.5.0.tar

      # see: https://github.com/super-linter/super-linter/releases/tag/v8.5.0
      - uses: super-linter/super-linter/slim@v8.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true

          VALIDATE_BASH: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_TERRAFORM_FMT: true
          VALIDATE_TERRAFORM_TFLINT: true

          FILTER_REGEX_EXCLUDE: (\.terraform/|terraform/.*\.terraform/)
          TERRAFORM_TFLINT_CONFIG_FILE: 01-terraform/.tflint.hcl